force-app/main/default/objects/Lead/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>The budget specified on the web enquiry form</description>
    <inlineHelpText>The budget specified on the web enquiry form</inlineHelpText>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/External_Reference__c.field-meta.xml
<CustomField>
    <fullName>External_Reference__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The unique Identifier for a web enquiry</description>
    <externalId>true</externalId>
    <inlineHelpText>The unique Identifier for a web enquiry</inlineHelpText>
    <label>External Reference</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/utils/WebApplicationProcessor.cls
public inherited sharing class WebApplicationProcessor {
    public void process(WebEnquiry webEnquiry) {
        //logic for processing
        // firstly check if person exists in the system, checking on the email address/phone number is likely the most solid solution
        List<Lead> existingContacts = [
            SELECT Id, Email, Phone
            FROM Lead
            WHERE Email = :webEnquiry.email OR Phone = :webEnquiry.phone
            LIMIT 1
        ];

        if (!existingContacts.isEmpty()) {
            // if the contact exists, we can update their details with the new information from the web enquiry
            Lead existingContact = existingContacts[0];
            existingContact.FirstName = webEnquiry.firstName;
            existingContact.LastName = webEnquiry.lastName;
            existingContact.Email = webEnquiry.email;
            existingContact.Phone = webEnquiry.phone;
        } else {
            createLead(webEnquiry);
        }
    }

    private void createLead(WebEnquiry webEnquiry) {
        // webEnquiry has already passed its initial checks, so it's safe to attempt the insert here
        Lead newLead = new Lead(
            FirstName = webEnquiry.firstName,
            LastName = webEnquiry.lastName,
            Company = webEnquiry.companyName,
            Email = webEnquiry.email,
            Phone = webEnquiry.phone,
            PostalCode = webEnquiry.postcode,
            Title = webEnquiry.enquirySubject,
            Description = webEnquiry.enquiryDescription,
            LeadSource = 'Web',
            Budget__c = webEnquiry.estimatedBudget,
            External_Reference__c = webEnquiry.externalReference
        );

        try {
            insert newLead;
        } catch (DmlException dmlEx) {
            throw new DmlException('Failed to create Lead from web enquiry: ' + dmlEx.getMessage(), dmlEx);
        }
    }
}